to_delete_trigger = [ "dd", "oi", "дд", "ой",]
to_delete_argument = "-"
blacklist_chats = []

[VK]
user_token = ""
bot_token = ""
user_id = 0
group_id = 0

[telegram]
telegram_bot_token = ""
telegram_id = 0

[qiwi]
qiwi_token = ""
qiwi_phone = 0
2fa_payment = false

[commands]
social = true
system = true
messages = true
to_delete = true
get_balance = true
payment = false
logger = true

[logger]
delete_notification = false
edit_notification = false
