[vk]
user_token = ""
group_token = ""
commands_prefix = '/'
delete_command_after = true
deactivate_modules = []

[to_delete]
to_delete_trigger = ["дд"]
to_delete_argument = "-"

[logger]
delete_notification = true
edit_notification = false

# Для разработчиков
[database]
url = 'sqlite+aiosqlite:///database.sqlite'

[logging]
level = 20
format = '[%(levelname)s] %(asctime)s - %(name)s - %(message)s'
