"""init

Revision ID: 0ac59cdd5c87
Revises: 
Create Date: 2022-08-18 18:49:17.364201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ac59cdd5c87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('user_token', sa.Text(), nullable=True),
    sa.Column('group_token', sa.Text(), nullable=True),
    sa.Column('commands_prefix', sa.String(length=8), nullable=True),
    sa.Column('delete_command_after', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('owner_id')
    )
    op.create_index(op.f('ix_sessions_owner_id'), 'sessions', ['owner_id'], unique=True)
    op.create_table('templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trigger', sa.String(length=64), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_owner_id'), 'templates', ['owner_id'], unique=False)
    op.create_index(op.f('ix_templates_trigger'), 'templates', ['trigger'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('document', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_template_id'), 'attachments', ['template_id'], unique=False)
    op.create_table('deactivate_modules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module', sa.Text(), nullable=True),
    sa.Column('session_owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_owner_id'], ['sessions.owner_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_deactivate_modules_session_owner_id'), 'deactivate_modules', ['session_owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deactivate_modules_session_owner_id'), table_name='deactivate_modules')
    op.drop_table('deactivate_modules')
    op.drop_index(op.f('ix_attachments_template_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_templates_trigger'), table_name='templates')
    op.drop_index(op.f('ix_templates_owner_id'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_sessions_owner_id'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
