"""added group_id column to sessions table

Revision ID: 25fc8a87aa8c
Revises: 0ac59cdd5c87
Create Date: 2022-09-05 15:38:29.861240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25fc8a87aa8c'
down_revision = '0ac59cdd5c87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('group_id', sa.Integer(), nullable=True))
    op.drop_index('ix_sessions_owner_id', table_name='sessions')
    op.create_index(op.f('ix_sessions_owner_id'), 'sessions', ['owner_id'], unique=False)
    op.create_index(op.f('ix_sessions_group_id'), 'sessions', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_group_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_owner_id'), table_name='sessions')
    op.create_index('ix_sessions_owner_id', 'sessions', ['owner_id'], unique=False)
    op.drop_column('sessions', 'group_id')
    # ### end Alembic commands ###
